language: java

jdk:
  - oraclejdk7
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

before_install:
  - export JAVA7_HOME=/usr/lib/jvm/java-7-oracle
  - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
  - export JAVA_HOME=$JAVA7_HOME

before_script:
    - chmod +x gradlew
    - chmod +x .script/deploy_artifacts.sh

script:
  - ./gradlew clean build --info

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - .script/deploy_artifacts.sh

notifications:
  email: false