language: java

jdk:
  - oraclejdk7

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

before_script:
    - chmod +x gradlew
    - chmod +x .script/deploy_artifacts.sh

script:
  - ./gradlew clean build --info

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - .script/deploy_artifacts.sh

notifications:
  email: false